/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DataNode */

#ifndef _Included_DataNode
#define _Included_DataNode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DataNode
 * Method:    helloFromC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DataNode_helloFromC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
